# Generated by Django 5.0.3 on 2024-04-28 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShareJourneysApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diadiemdungchan',
            name='thoiGianDung',
        ),
        migrations.AddField(
            model_name='diadiemdungchan',
            name='khoangThoiGian',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='posts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL),
        ),
    ]
