# Generated by Django 5.0.3 on 2024-04-28 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShareJourneysApp', '0004_alter_commenttick_cmttick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenttick',
            name='cmtTick',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticks', to='ShareJourneysApp.comments'),
        ),
    ]
