# Generated by Django 5.0.3 on 2024-05-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShareJourneysApp', '0005_alter_commenttick_cmttick'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diadiemdungchan',
            name='khoangThoiGian',
        ),
        migrations.AddField(
            model_name='diadiemdungchan',
            name='ThoiGianDuKien',
            field=models.DateTimeField(default='2024-06-30T00:00:00Z'),
        ),
    ]
